### PR TITLE
Avoid name mangling of Fortran symbol.

### PR DESCRIPTION
**Pull request by dhermes**
I'm making this change from the web UI for convenience. If you think it's a worthwhile change, I can track down all of the uses of the mangled `frtfunc_` and update them.

### CODE REVIEW

**Comment by dhermes** [comment]
Also, if you want to change the behavior of the Fortran code so that the signatures match, e.g.

```c
const char* frtfunc();
const char* cppfunc();
const char* rustfunc();
```

That is totally doable and I'm happy to send a change.

**ASIDE**: I've never seen Fortran abbreviated as `frt`.

**Comment by jpakkane** [comment]
Sure, go ahead. Please add a comment in there to explain why that is done and how things might break if it is done wrong.

**Comment by dhermes** [comment]
@jpakkane PTAL. I updated from old F77 syntax to modern syntax (i.e. post Fortran 90, hence the `.f90` file extension). It's a bit icky as far as Fortran code does, but it's not so bad to stick this square peg in a round hole.

I built locally and made sure it works, but I'm a bit nervous about the returned pointer to I'm poking a bit more.

The pre-"Fortran 90" Fortran was actually the all-caps **FORTRAN**, but the modern version is capitalized in a normal way. How do you feel about updating the project tagline "A Python extension module that uses C, C++, FORTRAN and Rust" to use "Fortran" instead?

**Comment by jpakkane** [comment]
Sounds good.

**Comment by dhermes** [comment]
@jpakkane PTAL, I was able to appease my doubts. I dropped `save` (the Fortran equivalent of a `static` variable) and am manually allocating the new memory on every call. This escapes the stack as desired and gives a new result on every call (i.e. non-`static`)

**Comment by jpakkane** [comment]
But isn't that a memory leak?

I specifically chose to use static strings so that the code does not have to deal with ownership issues. The idea is to have the code be as simple as possible since this sample is not really about the code but about how the build system setup work.

**Comment by dhermes** [comment]
> But isn't that a memory leak?

Yes, I noted the behavior in the function. I'll just revert the last commit in this PR so it's a `static` (i.e. `save`) string?

**Comment by dhermes** [comment]
@jpakkane Shall I revert the last commit?

**Comment by jpakkane** [comment]
Please do.

**Comment by dhermes** [comment]
@jpakkane Done.

**Comment by jpakkane** [comment]
Great, thanks.

**Pull request merged**
